# Configuration documentation:
#   https://embarkstudios.github.io/cargo-deny/index.html
#   https://github.com/EmbarkStudios/cargo-deny


# ----------------------------------------------------------------
# BANS
# ----------------------------------------------------------------

[bans]
# The graph highlighting used when creating dotgraphs for crates.
highlight = "simplest-path"
# The lint level for when a crate version requirement is set to `*`.
wildcards = "warn"
allow-wildcard-paths = true
# Lint level for when multiple versions of the same crate are detected.
multiple-versions = "warn"
# The default lint level for `default` features for workspace crates.
workspace-default-features = "allow"
# The default lint level for `default` features for external crates.
external-default-features = "allow"
deny = [
    # We are using rustls as the TLS implementation, so we shouldn't be linking
    # in OpenSSL too.
    #
    # If you're hitting this, you might want to take a look at what new
    # dependencies you have introduced and check if there's a way to depend on
    # rustls instead of OpenSSL (tip: check the crate's feature flags).
    { name = "openssl-sys" },
]

# ----------------------------------------------------------------
# SOURCES
# ----------------------------------------------------------------

[sources]
# What to do when encountering a repository from a host not in the allow list.
unknown-git = "deny"
# What to do when encountering a crate from a registry not in the allow list.
unknown-registry = "deny"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# ----------------------------------------------------------------
# ADVISORIES
# ----------------------------------------------------------------

[advisories]
version = 2
# The url(s) of the advisory databases to use.
db-urls = ["https://github.com/rustsec/advisory-db"]
# The path where the advisory database is cloned/fetched into.
db-path = "~/.cargo/advisory-db"
yanked = "deny"
ignore = [
  { id = "RUSTSEC-2024-0436", reason= "paste 1.0.15, no longer maintained"},
]


# ----------------------------------------------------------------
# LICENSES
# ----------------------------------------------------------------

[licenses]
# List of explicitly allowed licenses from https://spdx.org/licenses
allow = [
  "MIT",
  "ISC",
  "BSL-1.0",
  "Apache-2.0",
  "BSD-3-Clause",
  "MPL-2.0",
  "BSD-2-Clause",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
  "Zlib"
]

# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.95

# Allow specific licenses on a per-crate basis, instead of globally.
exceptions = [
  { allow = ["CC0-1.0"], name = "tiny-keccak", version = "*" },
  { allow = ["NCSA"], name = "libfuzzer-sys", version = "*" },
]
